import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";

import { Fira_Sans } from "next/font/google";

const font = Fira_Sans({
  subsets: ["latin"],
  variable: "--font-fira",
  weight: ["200", "300", "400", "500", "600", "700",  "800", "900"],
})

export const metadata: Metadata = {
  title: "Boxtrac",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('antialiased',font.className)}>
        {children}
      </body>
    </html>
  );
}
